const allRules = {
  'audit-argument-checks': require('./rules/audit-argument-checks'),
  'no-session': require('./rules/no-session'),
  'no-template-lifecycle-assignments': require('./rules/no-template-lifecycle-assignments'),
  'no-zero-timeout': require('./rules/no-zero-timeout'),
  'eventmap-params': require('./rules/eventmap-params'),
  'prefix-eventmap-selectors': require('./rules/prefix-eventmap-selectors'),
  'prefer-session-equals': require('./rules/prefer-session-equals'),
  'template-names': require('./rules/template-names'),
  'scope-dom-lookups': require('./rules/scope-dom-lookups'),
  'no-dom-lookup-on-created': require('./rules/no-dom-lookup-on-created'),
  'no-template-parent-data': require('./rules/no-template-parent-data'),
  'no-sync-mongo-methods-on-server': require('./rules/no-sync-mongo-methods-on-server'),
  'no-fibers-future-usage': require('./rules/no-fibers-future-usage'),
  'no-promise-fibers-usage': require('./rules/no-promise-fibers-usage'),
  'no-meteor-wrap-async-usage': require('./rules/no-meteor-wrap-async-usage'),
  'no-sync-user-methods-on-server': require('./rules/no-sync-user-methods-on-server'),
};

module.exports = {
  rules: allRules,
  configs: {
    recommended: {
      parserOptions: {
        ecmaVersion: 2024,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      plugins: ['@quave/meteor-quave'],
      rules: {
        '@quave/meteor-quave/audit-argument-checks': 2,
        '@quave/meteor-quave/no-session': 2,
        '@quave/meteor-quave/no-template-lifecycle-assignments': 2,
        '@quave/meteor-quave/no-zero-timeout': 2,
        '@quave/meteor-quave/eventmap-params': 2,
        '@quave/meteor-quave/prefix-eventmap-selectors': 0,
        '@quave/meteor-quave/prefer-session-equals': 0,
        '@quave/meteor-quave/template-names': 2,
        '@quave/meteor-quave/scope-dom-lookups': 0,
        '@quave/meteor-quave/no-dom-lookup-on-created': 0,
        '@quave/meteor-quave/no-template-parent-data': 0,
        '@quave/meteor-quave/no-sync-mongo-methods-on-server': 2,
        '@quave/meteor-quave/no-fibers-future-usage': 2,
        '@quave/meteor-quave/no-promise-fibers-usage': 2,
        '@quave/meteor-quave/no-meteor-wrap-async-usage': 2,
        '@quave/meteor-quave/no-sync-user-methods-on-server': 2,
      },
    },
  },
};
